### ISSUE TITLE
Erro no campo de busca

### ISSUE THREAD

**Issue by rafaelamiranda** [birobirobiro/downdevdetector#6]
Ao utilizar essa nova versão, sempre ao fazer uma pesquisa (usei o exemplo de "di") o primeiro card sempre vem com as informações do Notion.

![image](https://github.com/birobirobiro/downdevdetector/assets/28224363/6ad87474-5079-451d-b5fb-f7c635782da2)

**Comment by rafaelamiranda** [comment]
Revendo o print acabei de perceber que não é apenas o primeiro card

**Comment by birobirobiro** [comment]
> Revendo o print acabei de perceber que não é apenas o primeiro card

Obrigado pelo fix! Não tinha reparado que isso estava acontecendo, acabei de fazer o merge.
